language: python

python:
  - "3.6"

install:
  - pip install numpy

addons:
  apt:
    pachages:
      gfortran

script:
  - cd ${TRAVIS_BUILD_DIR}/submodule_python && python3 test.py
  - bash test.sh
  - cd ${TRAVIS_BUILD_DIR}/submodule_cpp && make
  - cd ${TRAVIS_BUILD_DIR}/submodule_fortran && make


