language: python

python:
  - "3.6"

install:
  - pip install numpy

script:
  - cd submodule_python && python3 test.py
  - bash test.sh
  - cd ../submodule_cpp && make
  - cd ../submodule_fortran && make


